name: fcal
version: '2.1.0'
summary: Command line calendar display
description: |
  fcal is a command line calendar display utility.  It will display a
  calendar on the command line with any month/year requested.  Defaults 
  to the current year.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core18

apps:
  fcal:
    command: bin/java -jar $SNAP/jar/cal.jar

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2020.12.21'
    maven-options: [install]

  cal:
    plugin: maven
    source: https://github.com/frossm/cal.git
    source-branch: master
    source-type: git
    after: [library]
