name: fcal
version: '2.3.15'
summary: Command line calendar display
description: |
  fCal is a command line calendar display utility.  It will display a
  calendar on the command line with any month/year requested.  Defaults 
  to the current year.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core18

# Enable faszter LZO compression
compression: lzo

apps:
  fcal:
    command: bin/java -jar $SNAP/jar/cal.jar

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2022.06.28'
    maven-options: [install]

  cal:
    plugin: maven
    source: https://github.com/frossm/cal.git
    source-branch: master
    source-type: git
    after: [library]
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs

plugs:
   cal-network:
      interface: network