name: fcal
title: fCal
version: '3.0.1'
summary: Command line calendar display
description: |
  fCal is a command line calendar utility.  It will display a
  calendar on the command line with any month/year requested.  Defaults 
  to the current year. fCal can also display local holidays. See help.

  Homepage:  https://github.com/frossm/cal

grade: stable
confinement: strict
base: core24
type: app

website: https://github.com/frossm/cal
contact: cal@fross.org
issues: https://github.com/frossm/cal/issues
license: MIT

platforms:
  amd64:
  arm64:

# Enable faster LZO compression
compression: lzo

apps:
  fcal:
    command: cal-wrapper
    environment:
      PATH: $SNAP/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64

    plugs:
       - network
       - home

parts:
  fcal:
    plugin: nil
    source: .
    build-attributes: [network]

    override-build: |
      # Ensure that gradlew is executable
      chmod +x gradlew
      
      # Build the application. Testing happened locally, so skip it here
      ./gradlew shadowJar -x test --console=plain
      
      # Move the shadowJar to the right place
      mkdir -p $SNAPCRAFT_PART_INSTALL/jar
      cp build/libs/*.jar $SNAPCRAFT_PART_INSTALL/jar/cal.jar
      
      # Move the wrapper and ensure it's executable
      cp $SNAPCRAFT_PROJECT_DIR/snap/local/cal-wrapper $SNAPCRAFT_PART_INSTALL/
      chmod +x $SNAPCRAFT_PART_INSTALL/cal-wrapper

    build-packages:
      - gradle
      - openjdk-21-jdk-headless

    stage-packages:
      - openjdk-21-jre-headless

